### ISSUE TITLE
logError is not defined out-of-the-box

### ISSUE THREAD

**Issue by bentito** [andrhamm/shotcaller#1]
```bash
$ npm install -g shotcaller

changed 9 packages, and audited 10 packages in 1s

3 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
~  $ shotcaller vt
/usr/local/lib/node_modules/shotcaller/dist/cvs.js/index.js:4805
  logError(
  ^

ReferenceError: logError is not defined
    at /usr/local/lib/node_modules/shotcaller/dist/cvs.js/index.js:4805:3
    at /usr/local/lib/node_modules/shotcaller/dist/cvs.js/index.js:4897:3
    at Object.<anonymous> (/usr/local/lib/node_modules/shotcaller/dist/cvs.js/index.js:4900:12)
    at Module._compile (node:internal/modules/cjs/loader:1092:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1121:10)
    at Module.load (node:internal/modules/cjs/loader:972:32)
    at Function.Module._load (node:internal/modules/cjs/loader:813:14)
    at Module.require (node:internal/modules/cjs/loader:996:19)
    at require (node:internal/modules/cjs/helpers:92:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/shotcaller/bin/shotcaller:2:1)
```

**Comment by andrhamm** [comment]
I guess having `dist/` in `.gitignore` was preventing the compiled source from being published to npm. Fixed in `1.1.0`
